# Generated by Django 5.1.5 on 2025-01-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_alter_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
