# Generated by Django 5.1.4 on 2024-12-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата первой отправки")),
                ("finished_at", models.DateTimeField(blank=True, verbose_name="Дата окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("finished", "Завершена"), ("created", "Создана"), ("launched", "Запущена")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылка",
                "ordering": ["status", "started_at"],
            },
        ),
        migrations.CreateModel(
            name="MailReceiver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(max_length=100, verbose_name="Ф.И.О")),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Тело")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("server_answer", models.TextField(verbose_name="Ответ почтового сервера")),
                ("mailing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.mailing")),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["mailing", "status", "attempt_at"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="receivers",
            field=models.ManyToManyField(to="mailing.mailreceiver"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="message", to="mailing.message"
            ),
        ),
    ]
