# Generated by Django 5.1.4 on 2024-12-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailingattempt_status_mailingunit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingunit",
            name="receivers",
            field=models.ManyToManyField(related_name="mailing_units", to="mailing.mailreceiver"),
        ),
    ]
