# Generated by Django 5.1.4 on 2024-12-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingunit_receivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingunit",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания отправки"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Текст"),
        ),
    ]
