# Generated by Django 5.1.4 on 2024-12-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_mailingunit_finished_at_alter_message_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingunit",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="mailing.message",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="mailingunit",
            name="status",
            field=models.CharField(
                choices=[("Finished", "Завершена"), ("Created", "Создана"), ("Launched", "Запущена")],
                default="Created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
