# Generated by Django 5.1.5 on 2025-01-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_mailingunit_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingunit",
            options={
                "ordering": ["-status", "started_at"],
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
