# Generated by Django 5.1.5 on 2025-01-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_mailingunit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_at", "mailing", "status"],
                "verbose_name": "Mailing Attempt",
                "verbose_name_plural": "Mailing Attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingunit",
            options={
                "ordering": ["-status", "started_at"],
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Mailing Unit",
                "verbose_name_plural": "Mailing Units",
            },
        ),
        migrations.AlterModelOptions(
            name="mailreceiver",
            options={"ordering": ["email"], "verbose_name": "Mail Receiver", "verbose_name_plural": "Mail Receivers"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["title"], "verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(choices=[("Success", "Success"), ("Failed", "Failed")], max_length=10),
        ),
        migrations.AlterField(
            model_name="mailingunit",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailingunit",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="message", to="mailing.message"
            ),
        ),
        migrations.AlterField(
            model_name="mailingunit",
            name="receivers",
            field=models.ManyToManyField(related_name="mailing_units", to="mailing.mailreceiver"),
        ),
        migrations.AlterField(
            model_name="mailingunit",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mailingunit",
            name="status",
            field=models.CharField(
                choices=[("Finished", "Finished"), ("Created", "Created"), ("Launched", "Launched")],
                default="Created",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mailreceiver",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mailreceiver",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
