# Generated by Django 5.1.5 on 2025-01-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0013_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_at", "mailing", "status"],
                "permissions": [("can_view_report", "Can view report")],
                "verbose_name": "Mailing Attempt",
                "verbose_name_plural": "Mailing Attempts",
            },
        ),
    ]
